language: go

go:
  - 1.5.x
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - master

before_install:
  - make clean
  - make dependencies

script: make all tests codecov

after_success:
  bash <(curl -s https://codecov.io/bash) -t f11efaf2-1d00-4b28-bc03-6c266581ce66